aws:
    region: '%env(DYNAMODB_REGION)%'
    version: '%env(DYNAMODB_VERSION)%'
    credentials:
        key: '%env(DYNAMODB_KEY)%'
        secret: '%env(DYNAMODB_SECRET)%'
    DynamoDb:
        endpoint: '%env(DYNAMODB_ENDPOINT)%'
    S3:
framework:
    secret: "Rosebud was the name of his sled."
