parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''
    redis_cache_url: '%env(REDIS_CACHE_URL)%' #TODO Find better solution to bypass env variable usage

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        charset: utf8
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        metadata_cache_driver:
            type: redis
            host: '%env(REDIS_CACHE_URL)%'
            port: 6379
        query_cache_driver:
            type: redis
            host: '%env(REDIS_CACHE_URL)%'
            port: 6379
        result_cache_driver:
            type: redis
            host: '%env(REDIS_CACHE_URL)%'
            port: 6379
        mappings:
            App:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine'
                prefix: 'App\Entity'
