lti1p3:
    key_chains:
        platformKey:
            key_set_name: "platformSet"
            public_key: "file://%kernel.project_dir%/config/secrets/dev/public.key"
            private_key: "file://%kernel.project_dir%/config/secrets/dev/private.key"
            private_key_passphrase: null
        toolKey:
            key_set_name: "toolSet"
            public_key: "file://%kernel.project_dir%/config/secrets/dev/public.key"
            private_key: "file://%kernel.project_dir%/config/secrets/dev/private.key"
            private_key_passphrase: null
        demoKey:
            key_set_name: "demoSet"
            public_key: "file://%kernel.project_dir%/config/secrets/dev/demo.key"
            private_key: null
            private_key_passphrase: null
    platforms:
        localPlatform:
            name: "Local platform"
            audience: "https://simple-roster.docker.localhost/platform"
            oidc_authentication_url: "https://simple-roster.docker.localhost/lti1p3/oidc/authentication"
            oauth2_access_token_url: "http://simple-roster-nginx/lti1p3/auth/platformKey/token"
    tools:
        localTool:
            name: "Local tool"
            audience: "https://simple-roster.docker.localhost/tool"
            oidc_initiation_url: "https://simple-roster.docker.localhost/lti1p3/oidc/initiation"
            launch_url: null
            deep_linking_url: null
        demoTool:
            name: "Demo tool"
            audience: "http://localhost:8888/tool"
            oidc_initiation_url: "http://localhost:8888/lti1p3/oidc/initiation"
            launch_url: "http://localhost:8888/tool/launch"
            deep_linking_url: null
    registrations:
        local:
            client_id: "client_id"
            platform: "localPlatform"
            tool: "localTool"
            deployment_ids:
                - "deploymentId1"
            platform_key_chain: "platformKey"
            tool_key_chain: "toolKey"
            platform_jwks_url: null
            tool_jwks_url: null
        demo:
            client_id: "demo"
            platform: "localPlatform"
            tool: "demoTool"
            deployment_ids:
                - "1"
            platform_key_chain: "platformKey"
            tool_key_chain: "demoKey"
            platform_jwks_url: null
            tool_jwks_url: null
