framework:
    messenger:
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # cache-warmup: 'sync://'
            cache-warmup:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: messenger.transport.symfony_serializer
                options:
                    account: 060438242623

        routing:
            'OAT\SimpleRoster\Message\RefreshUserCacheMessage': cache-warmup
