framework:
    messenger:
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            cache-warmup: 'sync://'
            rostering-file-uploaded: 'in-memory://'

        routing:
            'OAT\SimpleRoster\Message\WarmUpGroupedUserCacheMessage': cache-warmup
            'OAT\SimpleRoster\Message\RosteringFileUploadedMessage': rostering-file-uploaded
