framework:
    messenger:
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            cache-warmup: 'sync://'
            rostering-file-uploaded-pp:
                dsn: 'in-memory://'
                serializer: OAT\SimpleRoster\Messenger\Serializer\RosteringFileUploadedSerializer
            rostering-file-uploaded-sr:
                dsn: 'in-memory://'
                serializer: OAT\SimpleRoster\Messenger\Serializer\RosteringFileUploadedSerializer

        routing:
            'OAT\SimpleRoster\Message\WarmUpGroupedUserCacheMessage': cache-warmup
            'OAT\SimpleRoster\Message\RosteringFileUploadedMessage':
                - rostering-file-uploaded-pp
                - rostering-file-uploaded-sr
