monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        cache_warmup:
            level: debug
            type: stream
            path: '%kernel.logs_dir%/cache-warmup.%kernel.environment%.log'
            channels: ['cache_warmup']