security:
    encoders:
        App\Entity\User:
            algorithm: argon2i
            memory_cost: 1024
            time_cost: 1
            threads: 1

    providers:
        app_user_provider:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            anonymous: ~
            logout:
                path: logout
                success_handler: App\Security\LogoutSuccessHandler
            json_login:
                check_path: login
                remember_me: false

            # NOTE: the built-in "logout" mechanism is not usable here because it intercepts the request at the very beginning so no authorization happens

    access_control:
      - { path: ^/api/v1/healthcheck, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api/v1/bulk/assignments, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api/v1/lti/outcome, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api, roles: ROLE_USER }
