security:
    encoders:
        App\Entity\User:
            algorithm: auto
            memory_cost: 1024
            time_cost: 3

    providers:
        app_user_provider:
            id: App\Security\Provider\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_key:
            anonymous: ~
            pattern: '^%app.route_prefix%/bulk'
            guard:
                authenticators:
                    - App\Security\Authenticator\ApiKeyAuthenticator
            stateless: true

        api:
            anonymous: ~
            pattern: '^%app.route_prefix%'
            logout:
                path: logout
                success_handler: App\Security\Handler\LogoutSuccessHandler
            json_login:
                check_path: login
                remember_me: false

            # NOTE: the built-in "logout" mechanism is not usable here because it intercepts the request at the very beginning so no authorization happens

    access_control:
        - { path: '^%app.route_prefix%/healthcheck', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^%app.route_prefix%/lti/outcome', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^%app.route_prefix%', roles: ROLE_USER }
