language: php

dist: trusty

php:
  - 7.2

before_install:
  - composer install

script:
  - bin/phpunit
  - vendor/bin/infection --min-msi=70 --min-covered-msi=80
  - vendor/bin/phpstan analyse --level=4
