language: php

dist: trusty

php:
  - 7.2

env:
  - SYMFONY_DEPRECATIONS_HELPER=disabled

services:
  - docker

before_install:
  - docker-compose up -d
  - docker exec -it simple_roster_phpfpm composer install
  - docker exec -it simple_roster_phpfpm bin/console do:sc:up --force --dump-sql

script:
  - docker exec -it simple_roster_phpfpm bin/phpunit