language: php

dist: trusty

php:
  - 7.2

before_install:
  - yes '' | pecl install -f apcu
  - composer remove oat-sa/phing-tasks
  - composer install

script:
  - vendor/bin/infection --min-msi=80 --min-covered-msi=80
  - vendor/bin/phpstan -c phpstan.neon.travis.dist analyse --level=4
