language: php

dist: trusty

php:
  - 7.2

services:
  - docker

before_install:
  - docker-compose up -d
  - docker exec -it simple_roster_phpfpm composer install

script:
  - docker exec -it simple_roster_phpfpm bin/phpunit
