version: '3'

services:
    simple_roster_nginx:
        container_name: simple_roster_nginx
        image: nginx:stable
        networks:
          - simple_roster_network
        ports:
          - "80:80"
        volumes:
          - .:/var/www/html:cached
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
        working_dir: /etc/nginx/conf.d

    simple_roster_phpfpm:
        container_name: simple_roster_phpfpm
        build:
          context: ./docker/phpfpm
        expose:
          - 9000
        networks:
          - simple_roster_network
        volumes:
          - .:/var/www/html:cached
        working_dir: /var/www/html

    simple_roster_redis:
        container_name: simple_roster_redis
        image: redis
        command: ["redis-server", "--appendonly", "yes"]
        hostname: simple_roster_redis
        networks:
          - simple_roster_network
        ports:
          - "6379:6379"
        volumes:
          - simple_roster_redis_data:/data

    simple_roster_postgres:
        container_name: simple_roster_postgres
        image: postgres:9.5.15
        networks:
          - simple_roster_network
        ports:
          - "5432:5432"
        environment:
          - POSTGRES_USER=simple-roster
          - POSTGRES_PASSWORD=simple-roster
          - POSTGRES_DB=simple-roster
        volumes:
          - simple_roster_postgres_data:/var/lib/postgresql

    simple_roster_blackfire:
        container_name: simple_roster_blackfire
        image: blackfire/blackfire
        networks:
          - simple_roster_network
        ports:
          - "8707:8707"
        environment:
          - BLACKFIRE_SERVER_ID
          - BLACKFIRE_SERVER_TOKEN

volumes:
    simple_roster_redis_data:
       driver: local
    simple_roster_postgres_data:
       driver: local

networks:
    simple_roster_network:
       driver: bridge
