version: '3'

services:
    simple-roster-nginx:
        container_name: simple-roster-nginx
        image: nginx:stable
        networks:
            - simple-roster
            - oat-docker
        volumes:
            - .:/var/www/html:cached
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
        working_dir: /etc/nginx/conf.d
        labels:
            - "traefik.backend=simple-roster-nginx"
            - "traefik.frontend.rule=Host:simple-roster.docker.localhost"
            - "traefik.docker.network=oat-docker"
            - "traefik.port=80"

    simple-roster-phpfpm:
        container_name: simple-roster-phpfpm
        env_file:
            - .env.docker
        build:
            context: ./docker/phpfpm
        environment:
            COMPOSER_AUTH: $COMPOSER_AUTH
        expose:
            - 9000
        networks:
            - simple-roster
        volumes:
            - .:/var/www/html:cached
            - $COMPOSER_HOME:/root/.composer
        working_dir: /var/www/html

    simple-roster-redis:
        container_name: simple-roster-redis
        image: redis
        command: ["redis-server", "--appendonly", "yes"]
        hostname: simple-roster-redis
        networks:
            - simple-roster
        ports:
            - 6379
        volumes:
            - simple-roster-redis-volume:/data

    simple-roster-postgres:
        container_name: simple-roster-postgres
        image: postgres:9.5.15
        networks:
            - simple-roster
        ports:
            - 5432
        environment:
            - POSTGRES_USER=simple-roster
            - POSTGRES_PASSWORD=simple-roster
            - POSTGRES_DB=simple-roster
        volumes:
            - simple-roster-postgres-volume:/var/lib/postgres/data:cached

    simple-roster-blackfire:
        container_name: simple-roster-blackfire
        image: blackfire/blackfire
        networks:
            - simple-roster
        ports:
            - 8707
        environment:
            - BLACKFIRE_SERVER_ID
            - BLACKFIRE_SERVER_TOKEN

volumes:
    simple-roster-redis-volume:
        driver: local
    simple-roster-postgres-volume:
        driver: local

networks:
    simple-roster:
        driver: bridge
    oat-docker:
        external: true
