services:
    simple-roster-nginx:
        container_name: ${SIMPLE_ROSTER_NGINX_CONTAINER_NAME:-simple-roster-nginx}
        image: nginx:stable
        networks:
            - simple-roster
            - depp-delivery
            - oat-docker
        volumes:
            - .:/var/www/html:cached
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
        working_dir: /etc/nginx/conf.d
        labels:
            - "traefik.backend=simple-roster-nginx"
            - "traefik.frontend.rule=Host:simple-roster.docker.localhost"
            - "traefik.http.routers.simple-roster-nginx.rule=Host(`${SR_HOST:-simple-roster.docker.localhost}`)"
            - "traefik.docker.network=oat-docker"
            - "traefik.port=80"
