services:
    simple-roster-phpfpm:
        container_name: simple-roster-phpfpm${CONTAINER_SUFFIX}
        build:
            context: ./docker/phpfpm
        environment:
            COMPOSER_AUTH: '$COMPOSER_AUTH'
        expose:
            - 9000
        networks:
            - simple-roster
            - oat-docker
        volumes:
            - .:/var/www/html:cached
            - $COMPOSER_HOME:/root/.composer
        working_dir: /var/www/html

    simple-roster-worker:
        depends_on:
            - simple-roster-phpfpm
        container_name: simple-roster-worker${CONTAINER_SUFFIX}
        build:
            context: ./docker/phpfpm
        network_mode: service:simple-roster-phpfpm
        working_dir: /var/www/html
        volumes_from:
            - simple-roster-phpfpm
        environment:
            XDEBUG_CONFIG: client_host=${DOCKER_GATEWAY_HOST:-host.docker.internal} start_with_request=trigger
            XDEBUG_SESSION: PHPSTORM_WRK
            XDEBUG_MODE: ${XDEBUG_MODE:-off}
            PHP_IDE_CONFIG: serverName=simple-roster.docker.localhost
        command: >
            sh -lc 'php bin/console messenger:setup-transports --no-interaction || true;
            while true; do
            php bin/console messenger:consume rostering-file-uploaded-sr --time-limit=3600 --memory-limit=256M --no-interaction -vv;
            sleep 1;
            done'

    simple-roster-nginx:
        container_name: simple-roster-nginx${CONTAINER_SUFFIX}
        image: nginx:stable
        depends_on:
            - simple-roster-phpfpm
        networks:
            - simple-roster
            - oat-docker
        volumes:
            - .:/var/www/html:cached
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
        working_dir: /etc/nginx/conf.d
        labels:
            - "traefik.backend=simple-roster-nginx"
            - "traefik.http.routers.simple-roster-nginx.rule=Host(`${SR_HOST:-simple-roster.docker.localhost}`)"
            - "traefik.docker.network=oat-docker"
            - "traefik.port=80"

volumes:
    simple-roster-redis-volume:
        driver: local
    simple-roster-postgres-volume:
        driver: local

networks:
    simple-roster:
        driver: bridge
    depp-delivery:
        driver: bridge
    oat-docker:
        external: true
