include:
    - docker-compose-service.yml

services:
    simple-roster-redis:
        container_name: simple-roster-redis
        image: redis
        command: ["redis-server", "--appendonly", "yes"]
        hostname: simple-roster-redis
        networks:
            - simple-roster
        ports:
            - 6379
        volumes:
            - simple-roster-redis-volume:/data

    simple-roster-postgres:
        container_name: simple-roster-postgres
        image: postgres
        networks:
            - simple-roster
        ports:
            - 5432
        environment:
            - POSTGRES_USER=simple-roster
            - POSTGRES_PASSWORD=simple-roster
            - POSTGRES_DB=simple-roster
        volumes:
            - simple-roster-postgres-volume:/var/lib/postgres/data:cached

    simple-roster-localstack:
        container_name: simple-roster-localstack
        image: localstack/localstack
        ports:
            #- "4510-4559:4510-4559"
            - "4566:4566"
        environment:
            - SERVICES=s3,sqs
            - DEBUG=1
        networks:
            - simple-roster
            - oat-docker
        volumes:
            - "./localstack/init:/etc/localstack/init/ready.d"
        labels:
            - "traefik.backend=simple-roster-localstack"
            - "traefik.frontend.rule=Host:simple-roster.localstack.localhost"
            - "traefik.docker.network=oat-docker"
            - "traefik.port=4566"


    simple-roster-blackfire:
        container_name: simple-roster-blackfire
        image: blackfire/blackfire
        networks:
            - simple-roster
        ports:
            - 8707
        environment:
            - BLACKFIRE_SERVER_ID
            - BLACKFIRE_SERVER_TOKEN