version: '3'

include:
    - docker-compose-service.yml

services:
    simple-roster-phpfpm:
        container_name: simple-roster-phpfpm${CONTAINER_SUFFIX}
        env_file:
            - .env.docker
        build:
            context: ./docker/phpfpm
        environment:
            COMPOSER_AUTH: '$COMPOSER_AUTH'
        expose:
            - 9000
        networks:
            - simple-roster
            - oat-docker
        volumes:
            - .:/var/www/html:cached
            - $COMPOSER_HOME:/root/.composer
        working_dir: /var/www/html

    simple-roster-worker:
        depends_on:
            - simple-roster-phpfpm
        container_name: simple-roster-worker${CONTAINER_SUFFIX}
        env_file:
            - .env.docker
        build:
            context: ./docker/phpfpm
        network_mode: service:simple-roster-phpfpm
        working_dir: /var/www/html
        volumes_from:
            - simple-roster-phpfpm
        environment:
            XDEBUG_CONFIG: client_host=${DOCKER_GATEWAY_HOST:-host.docker.internal} start_with_request=trigger
            XDEBUG_SESSION: PHPSTORM_WRK
            XDEBUG_MODE: ${XDEBUG_MODE:-off}
            PHP_IDE_CONFIG: serverName=simple-roster.docker.localhost
        command: >
            sh -lc 'php bin/console messenger:setup-transports --no-interaction || true;
            while true; do
            php bin/console messenger:consume rostering-file-uploaded-sr --time-limit=3600 --memory-limit=256M --no-interaction -vv;
            sleep 1;
            done'

    simple-roster-redis:
        container_name: simple-roster-redis
        image: redis
        command: ["redis-server", "--appendonly", "yes"]
        hostname: simple-roster-redis
        networks:
            - simple-roster
        ports:
            - 6379
        volumes:
            - simple-roster-redis-volume:/data

    simple-roster-postgres:
        container_name: simple-roster-postgres
        image: postgres
        networks:
            - simple-roster
        ports:
            - 5432
        environment:
            - POSTGRES_USER=simple-roster
            - POSTGRES_PASSWORD=simple-roster
            - POSTGRES_DB=simple-roster
        volumes:
            - simple-roster-postgres-volume:/var/lib/postgres/data:cached

    simple-roster-blackfire:
        container_name: simple-roster-blackfire
        image: blackfire/blackfire
        networks:
            - simple-roster
        ports:
            - 8707
        environment:
            - BLACKFIRE_SERVER_ID
            - BLACKFIRE_SERVER_TOKEN

    simple-roster-localstack:
        container_name: simple-roster-localstack
        image: localstack/localstack
        ports:
            #- "4510-4559:4510-4559"
            - "4566:4566"
        environment:
            - SERVICES=s3,sqs
            - DEBUG=1
        networks:
            - simple-roster
            - oat-docker
        volumes:
            - "./localstack:/tmp/localstack"
            - "./localstack/init:/etc/localstack/init/ready.d"
            - "/var/run/docker.sock:/var/run/docker.sock"
        labels:
            - "traefik.backend=simple-roster-localstack"
            - "traefik.frontend.rule=Host:simple-roster.localstack.localhost"
            - "traefik.docker.network=oat-docker"
            - "traefik.port=4566"

volumes:
    simple-roster-redis-volume:
        driver: local
    simple-roster-postgres-volume:
        driver: local

networks:
    simple-roster:
        driver: bridge
    depp-delivery:
        driver: bridge
    oat-docker:
        external: true
