apiVersion: skaffold/v2beta2 
kind: Config
metadata:
  name: poc-demo
profiles:
  - name: dev
    activation:
    - kubeContext: minikube
      command: dev
    build:
      tagPolicy:
        sha256: {}
#        envTemplate:
#          template: "{{.IMAGE_NAME}}:dev"
      artifacts:
        - image: simple-roster-nginx
          context: .
          docker:
            dockerfile: ./docker/nginx/Dockerfile
            noCache: false
        - image: simple-roster
          context: .
          docker:
            dockerfile: ./docker/phpfpm/Dockerfile
            noCache: false
    deploy:
      helm:
        flags:
          global:
            - '--debug'
########### because of helm 3 changing from patch to replace, we need to use force=false for the moment
          upgrade:
            - '--force=false'
        releases: 
          - name: simple-roster
            namespace: poc
            chartPath: charts/poc
#            setValues:
#              defaultBackend.service.omitClusterIP: true
#              controller.service.omitClusterIP: true
#              service.omitClusterIP: true
            valuesFiles:
              - ./env.yaml
  - name: ci
    activation:
    - kubeContext:
      command: run
    build:
      googleCloudBuild:
        projectId: tao-ci-cd
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:{{.GITHUB_SHA}}"
      artifacts:
        - image: gcr.io/tao-ci-cd/poc/simple-roster-nginx
          context: .
          kaniko:
            image: gcr.io/kaniko-project/executor:0.20.0
            dockerfile: ./docker/nginx/Dockerfile
            cache:
              repo: gcr.io/tao-ci-cd/cache/poc/simple-roster-nginx

        - image: gcr.io/tao-ci-cd/poc/simple-roster
          context: .
          kaniko:
            image: gcr.io/kaniko-project/executor:0.20.0
            dockerfile: ./docker/phpfpm/Dockerfile
            cache:
              repo: gcr.io/tao-ci-cd/cache/poc/simple-roster
    deploy:
      helm:
        flags:
          global:
            - '--debug'
########### because of helm 3 changing from patch to replace, we need to use force=false for the moment
          upgrade:
            - '--force=false'
        releases:
          - name: simple-roster
            namespace: poc
            chartPath: charts/poc
            valuesFiles:
              - ./env.ci.version.yaml
              - ./env.ci.yaml