<?php

/**
 *  This program is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU General Public License
 *  as published by the Free Software Foundation; under version 2
 *  of the License (non-upgradable).
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 *  Copyright (c) 2022 (original work) Open Assessment Technologies S.A.
 */

declare(strict_types=1);

namespace OAT\SimpleRoster\Lti\Model;

use OAT\SimpleRoster\Entity\User;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class AutogeneratedUser
{
    protected string $name;
    protected string $password;
    protected string $group;

    public function __construct(string $name, string $password, string $group)
    {
        $this->name = $name;
        $this->password = $password;
        $this->group = $group;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function getPassword(): string
    {
        return $this->password;
    }

    public function getGroup(): string
    {
        return $this->group;
    }

    public function toEntity(UserPasswordHasherInterface $hasher): User
    {
        $model = new User();
        $model
            ->setUsername($this->name)
            ->setPassword($hasher->hashPassword($model, $this->password))
            ->addRole(User::ROLE_QA);

        if (!empty($this->group)) {
            $model->setGroupId($this->group);
        }

        return $model;
    }
}
