lti1p3:
    platforms:
        localPlatform:
            name: "Local platform"
            audience: "https://simple-roster.docker.localhost/platform"
            oidc_authentication_url: "https://simple-roster.docker.localhost/lti1p3/oidc/authentication"
            oauth2_access_token_url: "http://simple-roster-nginx/lti1p3/auth/platformKey/token"
