framework:
    messenger:
        transports:
            rostering-file-uploaded-pp:
                dsn: '%env(MESSENGER_ROSTERING_FILE_UPLOADED_PP_TRANSPORT_DSN)%'
                serializer: OAT\SimpleRoster\Messenger\Serializer\RosteringFileUploadedSerializer
            rostering-file-uploaded-sr:
                dsn: '%env(MESSENGER_ROSTERING_FILE_UPLOADED_SR_TRANSPORT_DSN)%'
                serializer: OAT\SimpleRoster\Messenger\Serializer\RosteringFileUploadedSerializer
