monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ['messenger']
