framework:
    messenger:
        transports:
            rostering-file-uploaded:
                dsn: '%env(MESSENGER_ROSTERING_FILE_UPLOADED_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
