healthCheck:
  path: '%app.route_prefix%/v1'
  methods: GET
  defaults: { _controller: OAT\SimpleRoster\Action\HealthCheck\HealthCheckAction }

getAccessToken:
  path: '%app.route_prefix%/v1/auth/token'

refreshAccessToken:
  path: '%app.route_prefix%/v1/auth/refresh-token'
  methods: POST
  defaults: { _controller: OAT\SimpleRoster\Action\Security\RefreshAccessTokenAction }

logout:
  path: '%app.route_prefix%/v1/auth/logout'

bulkCreateUsersAssignments:
  path: '%app.route_prefix%/v1/bulk/assignments'
  methods: POST
  defaults: { _controller: OAT\SimpleRoster\Action\Bulk\BulkCreateUsersAssignmentsAction }

bulkUpdateUsersAssignmentsState:
  path: '%app.route_prefix%/v1/bulk/assignments'
  methods: PATCH
  defaults: { _controller: OAT\SimpleRoster\Action\Bulk\BulkUpdateUsersAssignmentsStateAction }

getUserAssignments:
  path: '%app.route_prefix%/v1/assignments'
  methods: GET
  defaults: { _controller: OAT\SimpleRoster\Action\Assignment\ListUserAssignmentsAction }

getUserAssignmentLtiLink:
  path: '%app.route_prefix%/v1/assignments/{assignmentId}/lti-link'
  methods: GET
  defaults: { _controller: OAT\SimpleRoster\Action\Lti\GetUserAssignmentLtiLinkAction }

updateLti1p1Outcome:
  path: '%app.route_prefix%/v1/lti1p1/outcome'
  methods: POST
  defaults: { _controller: OAT\SimpleRoster\Action\Lti\UpdateLti1p1OutcomeAction }

getLineItems:
  path: '%app.route_prefix%/v1/line-items'
  methods: GET
  defaults: { _controller: OAT\SimpleRoster\Action\LineItem\ListLineItemsAction }

createLineItem:
  path: '%app.route_prefix%/v1/line-items'
  methods: POST
  defaults: { _controller: OAT\SimpleRoster\Action\LineItem\CreateLineItemAction }

updateLti1p3Outcome:
  path: '%app.route_prefix%/v1/lti1p3/outcome'
  methods: POST
  controller: app.service.basic_outcome_controller

updateLineItems:
  path: '%app.route_prefix%/v1/web-hooks/update-line-items'
  methods: POST
  defaults: { _controller: OAT\SimpleRoster\Action\WebHook\UpdateLineItemsWebhookAction }

bulkCreateUsers:
  path: '%app.route_prefix%/v1/bulk-create-users'
  methods: POST
  defaults: { _controller: OAT\SimpleRoster\Action\CreateEntity\BulkCreateUsersAction }

listLtiInstances:
  path: '%app.route_prefix%/v1/lti-instance/list'
  methods: GET
  defaults: { _controller: OAT\SimpleRoster\Action\LtiInstance\ListAction }

createLtiInstances:
  path: '%app.route_prefix%/v1/lti-instance'
  methods: POST
  defaults: { _controller: OAT\SimpleRoster\Action\LtiInstance\CreateAction }

updateLtiInstance:
  path: '%app.route_prefix%/v1/lti-instance/{ltiInstanceId}'
  methods: PUT
  defaults: { _controller: OAT\SimpleRoster\Action\LtiInstance\UpdateAction }

deleteLtiInstance:
  path: '%app.route_prefix%/v1/lti-instance/{ltiInstanceId}'
  methods: DELETE
  defaults: { _controller: OAT\SimpleRoster\Action\LtiInstance\DeleteAction }