healthCheck:
  path: '%app.route_prefix%/v1/healthcheck'
  methods: GET
  defaults: { _controller: OAT\SimpleRoster\Action\HealthCheck\HealthCheckAction }

login:
  path: '%app.route_prefix%/v1/auth/login'
  methods: POST
  defaults: { _controller: OAT\SimpleRoster\Action\Security\LoginAction }

logout:
  path: '%app.route_prefix%/v1/auth/logout'

bulkCreateUsersAssignments:
  path: '%app.route_prefix%/v1/bulk/assignments'
  methods: POST
  defaults: { _controller: OAT\SimpleRoster\Action\Bulk\BulkCreateUsersAssignmentsAction }

bulkUpdateUsersAssignmentsState:
  path: '%app.route_prefix%/v1/bulk/assignments'
  methods: PATCH
  defaults: { _controller: OAT\SimpleRoster\Action\Bulk\BulkUpdateUsersAssignmentsStateAction }

getUserAssignments:
  path: '%app.route_prefix%/v1/assignments'
  methods: GET
  defaults: { _controller: OAT\SimpleRoster\Action\Assignment\ListUserAssignmentsAction }

getUserAssignmentLtiLink:
  path: '%app.route_prefix%/v1/assignments/{assignmentId}/lti-link'
  methods: GET
  defaults: { _controller: OAT\SimpleRoster\Action\Lti\GetUserAssignmentLtiLinkAction }

updateLti1p1Outcome:
  path: '%app.route_prefix%/v1/lti1p1/outcome'
  methods: POST
  defaults: { _controller: OAT\SimpleRoster\Action\Lti\UpdateLti1p1OutcomeAction }

updateLti1p3Outcome:
  path: '%app.route_prefix%/v1/lti1p3/outcome'
  methods: POST
  defaults: { _controller: OAT\SimpleRoster\Action\Lti\UpdateLti1p3OutcomeAction }
