login:
  path: /api/v1/auth/login
  methods: POST
  defaults: { _controller: App\Action\Security\LoginAction }

logout:
  path: /api/v1/auth/logout

bulkCreateUsersAssignments:
  path: /api/v1/bulk/assignments
  methods: POST
  defaults: { _controller: App\Action\Bulk\BulkCreateUsersAssignmentsAction }

bulkUpdateUsersAssignmentsState:
  path: /api/v1/bulk/assignments
  methods: PATCH
  defaults: { _controller: App\Action\Bulk\BulkUpdateUsersAssignmentsStateAction }

getUserAssignments:
  path: /api/v1/assignments
  methods: GET
  defaults: { _controller: App\Action\Assignment\ListUserAssignmentsAction }

getUserAssignmentLtiLink:
  path: /api/v1/assignments/{assignmentId}/lti-link
  methods: GET
  defaults: { _controller: App\Action\Lti\GetUserAssignmentLtiLinkAction }

updateLtiOutcome:
  path: /api/v1/lti/outcome
  methods: POST
  defaults: { _controller: App\Action\Lti\UpdateLtiOutcomeAction }

