healthCheck:
  path: '%app.route_prefix%/healthcheck'
  methods: GET
  defaults: { _controller: OAT\SimpleRoster\Action\HealthCheck\HealthCheckAction }

login:
  path: '%app.route_prefix%/auth/login'
  methods: POST
  defaults: { _controller: OAT\SimpleRoster\Action\Security\LoginAction }

logout:
  path: '%app.route_prefix%/auth/logout'

bulkCreateUsersAssignments:
  path: '%app.route_prefix%/bulk/assignments'
  methods: POST
  defaults: { _controller: OAT\SimpleRoster\Action\Bulk\BulkCreateUsersAssignmentsAction }

bulkUpdateUsersAssignmentsState:
  path: '%app.route_prefix%/bulk/assignments'
  methods: PATCH
  defaults: { _controller: OAT\SimpleRoster\Action\Bulk\BulkUpdateUsersAssignmentsStateAction }

getUserAssignments:
  path: '%app.route_prefix%/assignments'
  methods: GET
  defaults: { _controller: OAT\SimpleRoster\Action\Assignment\ListUserAssignmentsAction }

getUserAssignmentLtiLink:
  path: '%app.route_prefix%/assignments/{assignmentId}/lti-link'
  methods: GET
  defaults: { _controller: OAT\SimpleRoster\Action\Lti\GetUserAssignmentLtiLinkAction }

updateLtiOutcome:
  path: '%app.route_prefix%/lti/outcome'
  methods: POST
  defaults: { _controller: OAT\SimpleRoster\Action\Lti\UpdateLtiOutcomeAction }

