createUsersAssignments:
  path: /api/v1/assignments
  methods: POST
  defaults: { _controller: App\Action\CreateUsersAssignmentsAction }

getUserAssignments:
  path: /api/v1/assignments
  methods: GET
  defaults: { _controller: App\Action\ListUserAssignmentsAction }

cancelUsersAssigntments:
  path: /api/v1/assignments
  methods: DELETE
  defaults: { _controller: App\Action\CancelUsersAssignmentsAction }
