createUserAssignments:
  path: /api/v1/assignments
  methods: POST
  defaults: { _controller: App\Action\CreateUserAssignmentsAction }

getUserAssignments:
  path: /api/v1/assignments
  methods: GET
  defaults: { _controller: App\Action\ListUserAssignmentsAction }
