login:
  path: /api/v1/auth/login
  methods: POST
  defaults: { _controller: App\Action\LoginAction }

logout:
  path: /api/v1/auth/logout

createUserAssignments:
  path: /api/v1/assignments
  methods: POST
  defaults: { _controller: App\Action\CreateUserAssignmentsAction }

updateLtiOutcome:
  path: /api/v1/lti/outcome
  methods: POST
  defaults: { _controller: App\Action\UpdateLtiOutcomeAction }

getUserAssignments:
  path: /api/v1/assignments
  methods: GET
  defaults: { _controller: App\Action\ListUserAssignmentsAction }

getUserAssignmentLtiLink:
  path: /api/v1/assignments/{assignmentId}/lti-link
  methods: GET
  defaults: { _controller: App\Action\GetUserAssignmentLtiLinkAction }
