parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $debug: '%kernel.debug%'
            $ltiLaunchPresentationReturnUrl: '%env(LTI_LAUNCH_PRESENTATION_RETURN_URL)%'

    _instanceof:
        App\Ingester\Ingester\IngesterInterface:
            tags: ['app.ingester']
        App\Ingester\Source\IngesterSourceInterface:
            tags: ['app.ingester_source']
        App\EventListener\Doctrine\EntityListenerInterface:
            tags: ['doctrine.orm.entity_listener']

    app.session_storage.connection:
        class: Redis
        calls:
            - method: connect
              arguments:
                  - '%env(REDIS_SESSION_CACHE_URL)%'
                  - '%env(int:REDIS_SESSION_CACHE_PORT)%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Model,Migrations,Tests,Kernel.php}'

    App\Action\:
        resource: '../src/Action'
        tags: ['controller.service_arguments']

    App\Repository\UserRepository:
        arguments:
            $userCacheTtl: '%env(REDIS_DOCTRINE_USER_CACHE_TTL)%'

    App\Ingester\Registry\IngesterRegistry:
        arguments: [!tagged 'app.ingester']

    App\Ingester\Registry\IngesterSourceRegistry:
        arguments: [!tagged 'app.ingester_source']

    App\Ingester\Source\S3CsvIngesterSource:
        arguments:
            $client: '@aws.s3'
            $bucket: '%env(AWS_S3_INGEST_BUCKET)%'

    App\EventSubscriber\UserCacheInvalidationSubscriber:
        tags: ['doctrine.event_subscriber']

    App\Command\GarbageCollector\AssignmentGarbageCollectorCommand:
        arguments:
            $cleanUpInterval: '%env(ASSIGNMENT_STATE_INTERVAL_THRESHOLD)%'

    App\Command\Cache\DoctrineResultCacheWarmerCommand:
        arguments:
            $doctrineConfiguration: '@doctrine.orm.default_configuration'

    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@app.session_storage.connection'
