# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    app.route_prefix: '%env(resolve:APP_ROUTE_PREFIX)%'
    app.lti.load_balancing_strategy: '%env(resolve:LTI_INSTANCE_LOAD_BALANCING_STRATEGY)%'
    app.lti.key: '%env(resolve:LTI_KEY)%'
    app.lti.secret: '%env(resolve:LTI_SECRET)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $kernelDebug: '%kernel.debug%'
            $kernelEnvironment: '%kernel.environment%'
            $ltiInstances: '%ltiInstances%'
            $ltiLaunchPresentationReturnUrl: '%env(resolve:LTI_LAUNCH_PRESENTATION_RETURN_URL)%'
            $ltiLaunchPresentationLocale: '%env(resolve:LTI_LAUNCH_PRESENTATION_LOCALE)%'
            $ltiInstancesLoadBalancerEnabled: '%env(bool:LTI_ENABLE_INSTANCES_LOAD_BALANCER)%'
            $appApiKey: '%env(resolve:APP_API_KEY)%'
            $ltiKey: '%app.lti.key%'
            $ltiSecret: '%app.lti.secret%'
            $userCacheTtl: '%env(REDIS_DOCTRINE_USER_CACHE_TTL)%'

    _instanceof:
        App\Ingester\Ingester\IngesterInterface:
            tags: ['app.ingester']
        App\Ingester\Source\IngesterSourceInterface:
            tags: ['app.ingester_source']
        App\EventListener\Doctrine\EntityListenerInterface:
            tags: ['doctrine.orm.entity_listener']

    app.session_storage.connection:
        class: Redis
        calls:
            -   method: connect
                arguments:
                    - '%env(resolve:REDIS_SESSION_CACHE_HOST)%'
                    - '%env(int:REDIS_SESSION_CACHE_PORT)%'

    app.doctrine_cache.connection:
        class: Redis
        calls:
            -   method: connect
                arguments:
                    - '%env(resolve:REDIS_DOCTRINE_CACHE_HOST)%'
                    - '%env(int:REDIS_DOCTRINE_CACHE_PORT)%'

    app.doctrine_cache.provider:
        class: Doctrine\Common\Cache\RedisCache
        calls:
            -   method: setRedis
                arguments:
                    - '@app.doctrine_cache.connection'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Model,Migrations,Tests,Kernel.php}'

    App\Action\:
        resource: '../src/Action'
        tags: ['controller.service_arguments']

    App\Ingester\Registry\IngesterRegistry:
        arguments: [!tagged 'app.ingester']

    App\Ingester\Registry\IngesterSourceRegistry:
        arguments: [!tagged 'app.ingester_source']

    App\Ingester\Source\S3CsvIngesterSource:
        arguments:
            $client: '@aws.s3'
            $bucket: '%env(AWS_S3_INGEST_BUCKET)%'

    App\EventSubscriber\UserCacheInvalidationSubscriber:
        tags: ['doctrine.event_subscriber']

    App\Command\GarbageCollector\AssignmentGarbageCollectorCommand:
        arguments:
            $cleanUpInterval: '%env(ASSIGNMENT_STATE_INTERVAL_THRESHOLD)%'

    App\Command\Cache\DoctrineResultCacheWarmerCommand:
        tags:
            - { name: monolog.logger, channel: cache_warmup }

    App\Logger\UserRequestSessionLogProcessor:
        tags:
            - { name: 'monolog.processor', channel: 'request' }
            - { name: 'monolog.processor', channel: 'app' }
            - { name: 'monolog.processor', channel: 'security' }

    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@app.session_storage.connection'

    App\Lti\LoadBalancer\LtiInstanceLoadBalancerInterface:
        factory: '@App\Lti\LoadBalancer\LtiInstanceLoadBalancerFactory'
        arguments:
            - '%app.lti.load_balancing_strategy%'

    Ramsey\Uuid\UuidFactoryInterface:
        class: Ramsey\Uuid\UuidFactory

    App\Lti\Extractor\ReplaceResultSourceIdExtractor:
        arguments:
            $xmlNamespace: '%env(LTI_OUTCOME_XML_NAMESPACE)%'

    OAT\Library\Lti1p3Core\Security\User\UserAuthenticatorInterface:
        class: App\Security\Lti\OidcUserAuthenticator
