<?php

/**
 *  This program is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU General Public License
 *  as published by the Free Software Foundation; under version 2
 *  of the License (non-upgradable).
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 *  Copyright (c) 2022 (original work) Open Assessment Technologies S.A.
 */

declare(strict_types=1);

namespace OAT\SimpleRoster\Lti\Service\UserGenerator;

use Doctrine\ORM\OptimisticLockException;
use Doctrine\ORM\ORMException;
use OAT\SimpleRoster\DataTransferObject\AssignmentDto;
use OAT\SimpleRoster\DataTransferObject\AssignmentDtoCollection;
use OAT\SimpleRoster\DataTransferObject\UserDto;
use OAT\SimpleRoster\DataTransferObject\UserDtoCollection;
use OAT\SimpleRoster\Entity\User;
use OAT\SimpleRoster\Lti\Model\AutogeneratedUser;
use OAT\SimpleRoster\Model\AssignmentCollection;
use OAT\SimpleRoster\Model\UserCollection;
use OAT\SimpleRoster\Repository\Criteria\FindUserCriteria;
use OAT\SimpleRoster\Repository\NativeAssignmentRepository;
use OAT\SimpleRoster\Repository\NativeUserRepository;
use OAT\SimpleRoster\Repository\UserRepository;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class UserGeneratorDatabaseStorage implements UserGeneratorStateStorageInterface
{
    private UserRepository $userRepository;
    private UserPasswordHasherInterface $hasher;
    private UserDtoCollection $userDtoCollection;
    private AssignmentDtoCollection $assignmentDtoCollection;
    private NativeAssignmentRepository $nativeAssignmentRepository;
    private NativeUserRepository $nativeUserRepository;

    public function __construct(
        UserRepository $userRepository,
        UserPasswordHasherInterface $hasher,
        UserDtoCollection $userDtoCollection,
        AssignmentDtoCollection $assignmentDtoCollection,
        NativeUserRepository $nativeUserRepository,
        NativeAssignmentRepository $nativeAssignmentRepository
    ) {
        $this->userRepository = $userRepository;
        $this->hasher = $hasher;
        $this->userDtoCollection = $userDtoCollection;
        $this->assignmentDtoCollection = $assignmentDtoCollection;
        $this->nativeUserRepository = $nativeUserRepository;
        $this->nativeAssignmentRepository = $nativeAssignmentRepository;
    }

    /**
     * @param AutogeneratedUser[] $users
     *
     * @throws ORMException
     * @throws OptimisticLockException
     */
    public function insertUsers(iterable $users): UserCollection
    {
        $usernames = [];
        $this->userDtoCollection->clear();
        foreach ($users as $user) {
            $this->createUserDtoCollection($user);
            $usernames[] = $user->getName();
        }

        $this->nativeUserRepository->insertMultiple($this->userDtoCollection);

        return $this->userRepository->findAllByCriteria(
            (new FindUserCriteria())->addUsernameCriterion(...$usernames)
        );
    }

    public function insertAssignment(AssignmentCollection $assignments): void
    {
        $this->assignmentDtoCollection->clear();
        foreach ($assignments as $assignment) {
            $this->assignmentDtoCollection->add(
                new AssignmentDto(
                    $assignment->getState(),
                    $assignment->getLineItem()->getId(),
                    $assignment->getUser()->getUsername(),
                    $assignment->getUser()->getId()
                )
            );
        }

        $this->nativeAssignmentRepository->insertMultiple($this->assignmentDtoCollection);
    }

    public function createUserDtoCollection(object $user): void
    {
        $this->userDtoCollection->add(
            new UserDto(
                $user->getName(),
                $this->hasher->hashPassword(new User(), $user->getPassword()),
                $user->getGroup() ? $user->getGroup() : null
            )
        );
    }
}
