App\Entity\Infrastructure:
    type: entity
    table: infrastructures
    repositoryClass: App\Repository\InfrastructureRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: AUTO
    fields:
        label:
            type: string
            scale: 0
            length: 255
            unique: true
            nullable: false
            precision: 0
        ltiDirectorLink:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
            column: lti_director_link
        ltiKey:
            type: string
            scale: 0
            length: 255
            unique: true
            nullable: false
            precision: 0
            column: lti_key
        ltiSecret:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
            column: lti_secret
    lifecycleCallbacks: {  }
