App\Entity\User:
    type: entity
    table: users
    repositoryClass: App\Repository\UserRepository
    id:
        id:
            type: integer
            length: null
            nullable: false
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
            unique: true
            nullable: false
        password:
            type: string
            length: 255
            unique: false
            nullable: false
        roles:
            type: json_array
            length: null
            unique: false
            nullable: false
        groupId:
            type: string
            length: 255
            unique: false
            nullable: true
    oneToMany:
        assignments:
            targetEntity: App\Entity\Assignment
            cascade: ["persist"]
            fetch: LAZY
            mappedBy: user
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks: {  }
    entityListeners:
        App\EventListener\Doctrine\UserPasswordEncoderListener:
